#!/usr/bin/env bun
/**
 * Odoo-parity scorecard generator.
 *
 *   bun run scripts/parity-report.ts            # print summary, regenerate matrix
 *   bun run scripts/parity-report.ts --check    # CI mode: fail if matrix is stale
 *
 * Reads docs/parity/capabilities/<module>.json (see _schema.md), computes a
 * weighted parity % per scored module, and (re)writes docs/parity/parity-matrix.md.
 * Modules that exist in src/lib/modules but have no capability file are listed as
 * UNSCORED so breadth coverage is always visible.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dir, '..');
const CAP_DIR = path.join(ROOT, 'docs/parity/capabilities');
const MODULES_DIR = path.join(ROOT, 'src/lib/modules');
const MATRIX = path.join(ROOT, 'docs/parity/parity-matrix.md');

type Status = 'done' | 'partial' | 'missing';
interface Capability {
  id: string; name: string; odoo: boolean; status: Status; weight: number;
  epic?: string; verify?: string; notes?: string;
}
interface CapFile {
  module: string; odoo_app: string;
  current_maturity: string; target_maturity: string;
  capabilities: Capability[];
}

const SCORE: Record<Status, number> = { done: 1, partial: 0.5, missing: 0 };

function loadCapFiles(): CapFile[] {
  if (!fs.existsSync(CAP_DIR)) return [];
  return fs.readdirSync(CAP_DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(fs.readFileSync(path.join(CAP_DIR, f), 'utf8')) as CapFile)
    .sort((a, b) => a.module.localeCompare(b.module));
}

function allModuleSlugs(): string[] {
  if (!fs.existsSync(MODULES_DIR)) return [];
  return fs.readdirSync(MODULES_DIR)
    .filter((f) => f.endsWith('-module.ts'))
    .map((f) => f.replace(/-module\.ts$/, ''))
    .sort();
}

function parityPct(c: CapFile): { pct: number; done: number; partial: number; missing: number; total: number } {
  const odoo = c.capabilities.filter((x) => x.odoo);
  const denom = odoo.reduce((s, x) => s + x.weight, 0);
  const numer = odoo.reduce((s, x) => s + x.weight * SCORE[x.status], 0);
  const tally = (st: Status) => odoo.filter((x) => x.status === st).length;
  return {
    pct: denom === 0 ? 0 : Math.round((numer / denom) * 100),
    done: tally('done'), partial: tally('partial'), missing: tally('missing'),
    total: odoo.length,
  };
}

function bar(pct: number): string {
  const filled = Math.round(pct / 10);
  return '█'.repeat(filled) + '░'.repeat(10 - filled);
}

function render(files: CapFile[]): string {
  const scored = files.map((c) => ({ c, s: parityPct(c) }));
  const overall = scored.length
    ? Math.round(scored.reduce((s, x) => s + x.s.pct, 0) / scored.length)
    : 0;

  const scoredSlugs = new Set(files.map((f) => f.module));
  const unscored = allModuleSlugs().filter((m) => !scoredSlugs.has(m));

  const lines: string[] = [];
  lines.push('---');
  lines.push('title: Odoo Parity Matrix');
  lines.push('description: GENERATED by scripts/parity-report.ts — do not edit by hand.');
  lines.push('category: reference');
  lines.push('---');
  lines.push('');
  lines.push('# Odoo Parity Matrix');
  lines.push('');
  lines.push('> **GENERATED FILE.** Run `bun run scripts/parity-report.ts` to refresh.');
  lines.push('> Edit `docs/parity/capabilities/<module>.json` to change scores.');
  lines.push('');
  lines.push(`**Scored modules:** ${files.length}  ·  **Mean parity:** ${overall}%  ·  **Unscored modules:** ${unscored.length}`);
  lines.push('');
  lines.push('## Scored modules');
  lines.push('');
  lines.push('| Module | Odoo app | Maturity → target | Parity | Done/Partial/Missing | Open epics |');
  lines.push('|---|---|---|---|---|---|');
  for (const { c, s } of scored.sort((a, b) => a.s.pct - b.s.pct)) {
    const epics = [...new Set(c.capabilities.filter((x) => x.epic && x.status !== 'done').map((x) => x.epic))].join(', ') || '—';
    lines.push(`| **${c.module}** | ${c.odoo_app} | ${c.current_maturity} → ${c.target_maturity} | \`${bar(s.pct)}\` ${s.pct}% | ${s.done}/${s.partial}/${s.missing} | ${epics} |`);
  }
  lines.push('');
  if (unscored.length) {
    lines.push('## Unscored modules (breadth backlog)');
    lines.push('');
    lines.push('> Create `docs/parity/capabilities/<module>.json` for each — see `_schema.md`.');
    lines.push('');
    lines.push(unscored.map((m) => `\`${m}\``).join(' · '));
    lines.push('');
  }
  lines.push('## Foundational gaps (weight 3, still open)');
  lines.push('');
  lines.push('| Module | Capability | Status | Epic |');
  lines.push('|---|---|---|---|');
  for (const c of files) {
    for (const cap of c.capabilities) {
      if (cap.odoo && cap.weight >= 3 && cap.status !== 'done') {
        lines.push(`| ${c.module} | ${cap.name} | ${cap.status} | ${cap.epic ?? '—'} |`);
      }
    }
  }
  lines.push('');
  return lines.join('\n');
}

const files = loadCapFiles();
const out = render(files);
const check = process.argv.includes('--check');

if (check) {
  const existing = fs.existsSync(MATRIX) ? fs.readFileSync(MATRIX, 'utf8') : '';
  if (existing.trim() !== out.trim()) {
    console.error('✖ parity-matrix.md is stale. Run: bun run scripts/parity-report.ts');
    process.exit(1);
  }
  console.log('✓ parity-matrix.md is up to date');
} else {
  fs.writeFileSync(MATRIX, out + '\n');
  const scored = files.map((c) => ({ m: c.module, ...parityPct(c) }));
  const mean = scored.length ? Math.round(scored.reduce((s, x) => s + x.pct, 0) / scored.length) : 0;
  console.log(`Wrote ${path.relative(ROOT, MATRIX)}`);
  console.log(`Scored ${files.length} modules · mean parity ${mean}%`);
  for (const s of scored.sort((a, b) => a.pct - b.pct)) {
    console.log(`  ${String(s.pct).padStart(3)}%  ${s.m}  (${s.done}/${s.partial}/${s.missing})`);
  }
}
