#!/usr/bin/env bun
/**
 * Skills Export Script
 *
 * Exports every module's skillSeeds to a single versioned artifact:
 *   supabase/seed/module-skills.json
 *
 * This decouples the database skill-sync (scripts/sync-skills.ts) from the
 * frontend module graph — the sync tool reads the JSON, never imports React
 * code, and works against any Supabase/Postgres instance.
 *
 * Run this whenever a module's skillSeeds change (same idea as
 * scripts/templates-to-json.ts for templates):
 *   bun run scripts/skills-to-json.ts
 */
import { resolve, join } from 'node:path';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';

// Module definitions transitively import browser-only helpers (e.g. locale-packs
// read localStorage at import time). Shim them so the graph loads under Bun.
const noopStorage = { getItem: () => null, setItem: () => {}, removeItem: () => {}, clear: () => {}, key: () => null, length: 0 };
(globalThis as any).localStorage ??= noopStorage;
(globalThis as any).window ??= { localStorage: noopStorage, matchMedia: () => ({ matches: false, addEventListener() {}, removeEventListener() {} }) };

const ROOT = resolve(import.meta.dir, '..');
const OUT_DIR = join(ROOT, 'supabase', 'seed');

interface ModuleLike { id?: string; skillSeeds?: unknown[] }

const modules = await import(join(ROOT, 'src', 'lib', 'modules', 'index.ts')) as Record<string, unknown>;

const out: Array<{ moduleId: string; skills: unknown[] }> = [];
let total = 0;
for (const exported of Object.values(modules)) {
  const m = exported as ModuleLike;
  if (!m || typeof m !== 'object' || !m.id || !Array.isArray(m.skillSeeds) || m.skillSeeds.length === 0) continue;
  out.push({ moduleId: m.id, skills: m.skillSeeds });
  total += m.skillSeeds.length;
}

// Platform-level skills (src/lib/platform-seeds.ts) are not owned by any module —
// they must exist on every instance regardless of module toggles. Emit them as
// the pseudo-module `platform` so sync-skills / fleet drift detection cover them
// (previously they were invisible to the CLI sync path — a drift hole).
const platformSeeds = await import(join(ROOT, 'src', 'lib', 'platform-seeds.ts')) as { PLATFORM_SKILLS?: unknown[] };
if (Array.isArray(platformSeeds.PLATFORM_SKILLS) && platformSeeds.PLATFORM_SKILLS.length > 0) {
  out.push({ moduleId: 'platform', skills: platformSeeds.PLATFORM_SKILLS });
  total += platformSeeds.PLATFORM_SKILLS.length;
}
out.sort((a, b) => a.moduleId.localeCompare(b.moduleId));

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
const artifact = {
  _comment: 'Generated by scripts/skills-to-json.ts — DO NOT edit by hand. Run sync-skills.ts to apply to an instance.',
  generated_at: new Date().toISOString(),
  module_count: out.length,
  skill_count: total,
  modules: out,
};
writeFileSync(join(OUT_DIR, 'module-skills.json'), JSON.stringify(artifact, null, 2) + '\n');
console.log(`✅ Wrote supabase/seed/module-skills.json — ${out.length} modules, ${total} skills`);
