#!/usr/bin/env bun
/**
 * Seed Export Script
 *
 * Exports the three things an instance needs but cannot get from migrations,
 * as versioned artifacts under supabase/seed/:
 *   module-skills.json       every module's skillSeeds (+ platform seeds)
 *   module-automations.json  every module's automation seeds
 *   locale-packs.json        each accounting pack's chart of accounts
 *
 * This decouples the database sync (scripts/sync-skills.ts) from the frontend
 * module graph — the sync tool reads the JSON, never imports React code, and
 * works against any Supabase/Postgres instance.
 *
 * Automations and the chart were previously reachable ONLY from React:
 * automations from bootstrapModule(), the chart from topUpLocalePackSeeds().
 * An install where nobody opened the admin got neither — and FlowWink is sold
 * as agent-operated, so "nobody logs in" is a supported case, not an edge one.
 * Both cost us real bugs on 2026-07-20/21 (a fleet deploy that silently seeded
 * no automations, and a fresh install running on five accounts while the
 * bookkeeping RPCs posted to 1930).
 *
 * Run whenever module seeds or a locale pack change (same idea as
 * scripts/templates-to-json.ts for templates):
 *   bun run scripts/skills-to-json.ts
 */
import { resolve, join } from 'node:path';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';

// Module definitions transitively import browser-only helpers (e.g. locale-packs
// read localStorage at import time). Shim them so the graph loads under Bun.
const noopStorage = { getItem: () => null, setItem: () => {}, removeItem: () => {}, clear: () => {}, key: () => null, length: 0 };
(globalThis as any).localStorage ??= noopStorage;
(globalThis as any).window ??= { localStorage: noopStorage, matchMedia: () => ({ matches: false, addEventListener() {}, removeEventListener() {} }) };

const ROOT = resolve(import.meta.dir, '..');
const OUT_DIR = join(ROOT, 'supabase', 'seed');

interface ModuleLike { id?: string; skillSeeds?: unknown[]; automations?: unknown[] }

const modules = await import(join(ROOT, 'src', 'lib', 'modules', 'index.ts')) as Record<string, unknown>;

const out: Array<{ moduleId: string; skills: unknown[] }> = [];
const autos: Array<{ moduleId: string; automations: unknown[] }> = [];
let total = 0;
let autoTotal = 0;
for (const exported of Object.values(modules)) {
  const m = exported as ModuleLike;
  if (!m || typeof m !== 'object' || !m.id) continue;
  if (Array.isArray(m.skillSeeds) && m.skillSeeds.length > 0) {
    out.push({ moduleId: m.id, skills: m.skillSeeds });
    total += m.skillSeeds.length;
  }
  if (Array.isArray(m.automations) && m.automations.length > 0) {
    autos.push({ moduleId: m.id, automations: m.automations });
    autoTotal += m.automations.length;
  }
}

// Platform-level skills (src/lib/platform-seeds.ts) are not owned by any module —
// they must exist on every instance regardless of module toggles. Emit them as
// the pseudo-module `platform` so sync-skills / fleet drift detection cover them
// (previously they were invisible to the CLI sync path — a drift hole).
const platformSeeds = await import(join(ROOT, 'src', 'lib', 'platform-seeds.ts')) as { PLATFORM_SKILLS?: unknown[] };
if (Array.isArray(platformSeeds.PLATFORM_SKILLS) && platformSeeds.PLATFORM_SKILLS.length > 0) {
  out.push({ moduleId: 'platform', skills: platformSeeds.PLATFORM_SKILLS });
  total += platformSeeds.PLATFORM_SKILLS.length;
}
out.sort((a, b) => a.moduleId.localeCompare(b.moduleId));

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
const artifact = {
  _comment: 'Generated by scripts/skills-to-json.ts — DO NOT edit by hand. Run sync-skills.ts to apply to an instance.',
  generated_at: new Date().toISOString(),
  module_count: out.length,
  skill_count: total,
  modules: out,
};
writeFileSync(join(OUT_DIR, 'module-skills.json'), JSON.stringify(artifact, null, 2) + '\n');
console.log(`✅ Wrote supabase/seed/module-skills.json — ${out.length} modules, ${total} skills`);

// ── Automations ─────────────────────────────────────────────────────────────
autos.sort((a, b) => a.moduleId.localeCompare(b.moduleId));
writeFileSync(
  join(OUT_DIR, 'module-automations.json'),
  JSON.stringify(
    {
      _comment:
        'Generated by scripts/skills-to-json.ts — DO NOT edit by hand. Applied by sync-skills.ts, which inserts by name only (never updates), so an operator-edited schedule survives a sync.',
      generated_at: new Date().toISOString(),
      module_count: autos.length,
      automation_count: autoTotal,
      modules: autos,
    },
    null,
    2,
  ) + '\n',
);
console.log(`✅ Wrote supabase/seed/module-automations.json — ${autos.length} modules, ${autoTotal} automations`);

// ── Locale packs (chart of accounts) ────────────────────────────────────────
// Only the chart travels. Templates, adapters and year-end proposals are code
// (functions), not data, and cannot cross into a JSON artifact.
const lp = (await import(join(ROOT, 'src', 'lib', 'locale-packs', 'index.ts'))) as {
  LOCALE_PACKS?: Record<string, { id: string; label?: string; chart?: unknown[] }>;
  DEFAULT_LOCALE_ID?: string;
};
const packs = Object.values(lp.LOCALE_PACKS ?? {})
  .filter((p) => Array.isArray(p.chart) && p.chart.length > 0)
  .map((p) => ({ id: p.id, label: p.label ?? p.id, accounts: p.chart as unknown[] }))
  .sort((a, b) => a.id.localeCompare(b.id));
writeFileSync(
  join(OUT_DIR, 'locale-packs.json'),
  JSON.stringify(
    {
      _comment:
        'Generated by scripts/skills-to-json.ts — DO NOT edit by hand. sync-skills.ts inserts missing account codes for the instance\'s active pack, mirroring topUpLocalePackSeeds().',
      generated_at: new Date().toISOString(),
      default_pack: lp.DEFAULT_LOCALE_ID ?? null,
      packs,
    },
    null,
    2,
  ) + '\n',
);
console.log(
  `✅ Wrote supabase/seed/locale-packs.json — ${packs.length} pack(s), ${packs.reduce((n, p) => n + p.accounts.length, 0)} accounts`,
);

// Same artifact, bundled into agent-execute (the way _templates.json is) so
// install_template can activate a template's accounting locale and seed its
// chart without a browser session. Edge deploys only bundle the function's own
// directory, so supabase/seed/ is out of reach there.
const edgeCopy = join(ROOT, 'supabase', 'functions', 'agent-execute', '_locale-packs.json');
writeFileSync(
  edgeCopy,
  JSON.stringify({ default_pack: lp.DEFAULT_LOCALE_ID ?? null, packs }) + '\n',
);
console.log(`  ✅ supabase/functions/agent-execute/_locale-packs.json`);
