-- ============================================================================
-- se-bas2024: align every account NAME with the standard we claim to follow.
--
-- src/data/bas2024-accounts.ts was headed "BAS 2024 Chart of Accounts" and was
-- written by hand — 269 accounts, no import, no source. Compared against the
-- official workbook on 2026-08-09: 63 correct, 166 wrong names, 40 account
-- numbers not in BAS at all. Whole ranges shifted by one position; 7510
-- "Avskrivning inventarier" is BAS's "Arbetsgivaravgifter 31,42 %"; 1130
-- "Inventarier, verktyg och installationer" is BAS's "Mark".
--
-- Only NAMES change here. Account codes are what journal entries reference, so
-- existing bookkeeping is untouched — a renamed account keeps every line that
-- ever posted to it. What changes is that the label finally tells the truth.
--
-- Codes NOT in BAS 2024 (3010, 3041, 4020, 7020, …) are deliberately left
-- alone: instances may already have posted to them, and deleting an account
-- with history is worse than an account with a non-standard number. They are
-- tracked in KNOWN_NOT_IN_BAS in bas2024-chart.guardrails.test.ts and must only
-- shrink.
--
-- An operator who renamed an account keeps their wording: only rows still
-- carrying our old fabricated name are updated.
-- ============================================================================

BEGIN;

-- ON COMMIT DROP would take the table with the statement's own transaction in
-- psql's autocommit mode, so the whole thing runs as one explicit transaction.
CREATE TEMP TABLE _bas_names (account_code text PRIMARY KEY, account_name text);
INSERT INTO _bas_names (account_code, account_name) VALUES
  ('1010', 'Utvecklingsutgifter'),
  ('1020', 'Koncessioner m.m.'),
  ('1030', 'Patent'),
  ('1040', 'Licenser'),
  ('1050', 'Varumärken'),
  ('1060', 'Hyresrätter, tomträtter och liknande'),
  ('1070', 'Goodwill'),
  ('1088', 'Förskott för immateriella anläggningstillgångar'),
  ('1110', 'Byggnader'),
  ('1111', 'Byggnader på egen mark'),
  ('1119', 'Ackumulerade avskrivningar på byggnader'),
  ('1120', 'Förbättringsutgifter på annans fastighet'),
  ('1129', 'Ackumulerade avskrivningar på förbättringsutgifter på annans fastighet'),
  ('1130', 'Mark'),
  ('1150', 'Markanläggningar'),
  ('1159', 'Ackumulerade avskrivningar på markanläggningar'),
  ('1180', 'Pågående nyanläggningar och förskott för byggnader och mark'),
  ('1210', 'Maskiner och andra tekniska anläggningar'),
  ('1219', 'Ackumulerade avskrivningar på maskiner och andra tekniska anläggningar'),
  ('1220', 'Inventarier och verktyg'),
  ('1229', 'Ackumulerade avskrivningar på inventarier och verktyg'),
  ('1310', 'Andelar i koncernföretag'),
  ('1320', 'Långfristiga fordringar hos koncernföretag'),
  ('1350', 'Andelar och värdepapper i andra företag'),
  ('1360', 'Lån till delägare eller närstående enligt ABL, långfristig del'),
  ('1380', 'Andra långfristiga fordringar'),
  ('1410', 'Lager av råvaror'),
  ('1420', 'Lager av tillsatsmaterial och förnödenheter'),
  ('1440', 'Produkter i arbete'),
  ('1450', 'Lager av färdiga varor'),
  ('1510', 'Kundfordringar'),
  ('1520', 'Växelfordringar'),
  ('1530', 'Kontraktsfordringar'),
  ('1550', 'Konsignationsfordringar'),
  ('1560', 'Kundfordringar hos koncernföretag'),
  ('1580', 'Fordringar för kontokort och kuponger'),
  ('1610', 'Kortfristiga fordringar hos anställda'),
  ('1620', 'Upparbetad men ej fakturerad intäkt'),
  ('1630', 'Avräkning för skatter och avgifter (skattekonto)'),
  ('1640', 'Skattefordringar'),
  ('1650', 'Momsfordran'),
  ('1660', 'Kortfristiga fordringar hos koncernföretag'),
  ('1710', 'Förutbetalda hyreskostnader'),
  ('1790', 'Övriga förutbetalda kostnader och upplupna intäkter'),
  ('1810', 'Andelar i börsnoterade företag'),
  ('1890', 'Nedskrivning av kortfristiga placeringar'),
  ('1910', 'Kassa'),
  ('1920', 'PlusGiro'),
  ('1930', 'Företagskonto/checkkonto/affärskonto'),
  ('1940', 'Övriga bankkonton'),
  ('1950', 'Bankcertifikat'),
  ('1960', 'Koncernkonto moderföretag'),
  ('2010', 'Eget kapital'),
  ('2011', 'Egna varuuttag'),
  ('2013', 'Övriga egna uttag'),
  ('2018', 'Övriga egna insättningar'),
  ('2020', 'Eget kapital'),
  ('2030', 'Eget kapital'),
  ('2040', 'Eget kapital'),
  ('2050', 'Avsättning till expansionsfond'),
  ('2070', 'Ändamålsbestämda medel'),
  ('2072', 'Ändamål 2'),
  ('2080', 'Bundet eget kapital'),
  ('2081', 'Aktiekapital'),
  ('2090', 'Fritt eget kapital'),
  ('2091', 'Balanserad vinst eller förlust'),
  ('2099', 'Årets resultat'),
  ('2110', 'Periodiseringsfonder'),
  ('2150', 'Ackumulerade överavskrivningar'),
  ('2210', 'Avsättningar för pensioner enligt tryggandelagen'),
  ('2220', 'Avsättningar för garantier'),
  ('2250', 'Övriga avsättningar för skatter'),
  ('2290', 'Övriga avsättningar'),
  ('2310', 'Obligations- och förlagslån'),
  ('2350', 'Andra långfristiga skulder till kreditinstitut'),
  ('2410', 'Andra kortfristiga låneskulder till kreditinstitut'),
  ('2420', 'Förskott från kunder'),
  ('2440', 'Leverantörsskulder'),
  ('2450', 'Fakturerad men ej upparbetad intäkt'),
  ('2460', 'Leverantörsskulder till koncernföretag'),
  ('2470', 'Leverantörsskulder till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i'),
  ('2480', 'Checkräkningskredit, kortfristig'),
  ('2490', 'Övriga kortfristiga skulder till kreditinstitut, kunder och leverantörer'),
  ('2510', 'Skatteskulder'),
  ('2610', 'Utgående moms, 25 %'),
  ('2611', 'Utgående moms på försäljning inom Sverige, 25 %'),
  ('2614', 'Utgående moms omvänd skattskyldighet, 25 %'),
  ('2615', 'Utgående moms import av varor, 25 %'),
  ('2620', 'Utgående moms, 12 %'),
  ('2624', 'Utgående moms omvänd skattskyldighet, 12 %'),
  ('2625', 'Utgående moms import av varor, 12 %'),
  ('2630', 'Utgående moms, 6 %'),
  ('2634', 'Utgående moms omvänd skattskyldighet, 6 %'),
  ('2635', 'Utgående moms import av varor, 6 %'),
  ('2640', 'Ingående moms'),
  ('2641', 'Debiterad ingående moms'),
  ('2645', 'Beräknad ingående moms på förvärv från utlandet'),
  ('2650', 'Redovisningskonto för moms'),
  ('2660', 'Punktskatter'),
  ('2710', 'Personalskatt'),
  ('2730', 'Lagstadgade sociala avgifter och särskild löneskatt'),
  ('2731', 'Avräkning lagstadgade sociala avgifter'),
  ('2740', 'Avtalade sociala avgifter'),
  ('2750', 'Utmätning i lön m.m.'),
  ('2820', 'Kortfristiga skulder till anställda'),
  ('2890', 'Övriga kortfristiga skulder'),
  ('2891', 'Skulder under indrivning'),
  ('2898', 'Outtagen vinstutdelning'),
  ('2920', 'Upplupna semesterlöner'),
  ('2990', 'Övriga upplupna kostnader och förutbetalda intäkter'),
  ('3000', 'Försäljning inom Sverige'),
  ('3001', 'Försäljning inom Sverige, 25 % moms'),
  ('3002', 'Försäljning inom Sverige, 12 % moms'),
  ('3003', 'Försäljning inom Sverige, 6 % moms'),
  ('3004', 'Försäljning inom Sverige, momsfri'),
  ('3100', 'Försäljning av varor utanför Sverige'),
  ('3200', 'Försäljning VMB och omvänd moms'),
  ('3300', 'Försäljning av tjänster utanför Sverige'),
  ('3500', 'Fakturerade kostnader (gruppkonto)'),
  ('3530', 'Fakturerade tull- och speditionskostnader m.m.'),
  ('3540', 'Faktureringsavgifter'),
  ('3600', 'Rörelsens sidointäkter (gruppkonto)'),
  ('3700', 'Intäktskorrigeringar (gruppkonto)'),
  ('3740', 'Öres- och kronutjämning'),
  ('3960', 'Valutakursvinster på fordringar och skulder av rörelsekaraktär'),
  ('3970', 'Vinst vid avyttring av immateriella och materiella anläggningstillgångar'),
  ('4000', 'Inköp av varor från Sverige'),
  ('4500', 'Övriga momspliktiga inköp'),
  ('4600', 'Legoarbeten och underentreprenader (gruppkonto)'),
  ('5010', 'Lokalhyra'),
  ('5020', 'El för belysning'),
  ('5030', 'Värme'),
  ('5040', 'Vatten och avlopp'),
  ('5050', 'Lokaltillbehör'),
  ('5060', 'Städning och renhållning'),
  ('5090', 'Övriga lokalkostnader'),
  ('5410', 'Förbrukningsinventarier'),
  ('5420', 'Programvaror'),
  ('5430', 'Transportinventarier'),
  ('5460', 'Förbrukningsmaterial'),
  ('5500', 'Reparation och underhåll (gruppkonto)'),
  ('5600', 'Kostnader för transportmedel (gruppkonto)'),
  ('5610', 'Personbilskostnader'),
  ('5620', 'Lastbilskostnader'),
  ('5630', 'Truckkostnader'),
  ('5640', 'Kostnader för arbetsmaskiner'),
  ('5650', 'Traktorkostnader'),
  ('5800', 'Resekostnader (gruppkonto)'),
  ('5810', 'Biljetter'),
  ('5820', 'Hyrbilskostnader'),
  ('5831', 'Kost och logi i Sverige'),
  ('5832', 'Kost och logi i utlandet'),
  ('5910', 'Annonsering'),
  ('5920', 'Utomhus- och trafikreklam'),
  ('5930', 'Reklamtrycksaker och direktreklam'),
  ('6000', 'Övriga försäljningskostnader (gruppkonto)'),
  ('6040', 'Kontokortsavgifter'),
  ('6070', 'Representation'),
  ('6071', 'Representation, avdragsgill'),
  ('6072', 'Representation, ej avdragsgill'),
  ('6110', 'Kontorsmateriel'),
  ('6200', 'Tele och post (gruppkonto)'),
  ('6210', 'Telekommunikation'),
  ('6230', 'Datakommunikation'),
  ('6250', 'Postbefordran'),
  ('6310', 'Företagsförsäkringar'),
  ('6320', 'Självrisker vid skada'),
  ('6350', 'Förluster på kundfordringar'),
  ('6410', 'Styrelsearvoden som inte är lön'),
  ('6420', 'Ersättningar till revisor'),
  ('6530', 'Redovisningstjänster'),
  ('6540', 'IT-tjänster'),
  ('6550', 'Konsultarvoden'),
  ('6560', 'Serviceavgifter till branschorganisationer'),
  ('6570', 'Bankkostnader'),
  ('6580', 'Advokat- och rättegångskostnader'),
  ('6590', 'Övriga externa tjänster'),
  ('6800', 'Inhyrd personal (gruppkonto)'),
  ('6900', 'Övriga externa kostnader (gruppkonto)'),
  ('6910', 'Licensavgifter och royalties'),
  ('6950', 'Tillsynsavgifter myndigheter'),
  ('6970', 'Tidningar, tidskrifter och facklitteratur'),
  ('6980', 'Föreningsavgifter'),
  ('6990', 'Övriga externa kostnader'),
  ('7010', 'Löner till kollektivanställda'),
  ('7030', 'Löner till kollektivanställda (utlandsanställda)'),
  ('7080', 'Löner till kollektivanställda för ej arbetad tid'),
  ('7082', 'Semesterlöner till kollektivanställda'),
  ('7090', 'Förändring av semesterlöneskuld'),
  ('7210', 'Löner till tjänstemän'),
  ('7220', 'Löner till företagsledare'),
  ('7230', 'Löner till tjänstemän och ftgsledare (utlandsanställda)'),
  ('7290', 'Förändring av semesterlöneskuld'),
  ('7310', 'Kontanta extraersättningar'),
  ('7320', 'Traktamenten vid tjänsteresa'),
  ('7321', 'Skattefria traktamenten, Sverige'),
  ('7330', 'Bilersättningar'),
  ('7331', 'Skattefria bilersättningar'),
  ('7350', 'Ersättningar för föreskrivna arbetskläder'),
  ('7380', 'Kostnader för förmåner till anställda'),
  ('7385', 'Kostnader för fri bil'),
  ('7510', 'Arbetsgivaravgifter 31,42 %'),
  ('7720', 'Nedskrivningar av byggnader och mark'),
  ('7810', 'Avskrivningar på immateriella anläggningstillgångar'),
  ('7820', 'Avskrivningar på byggnader och markanläggningar'),
  ('7830', 'Avskrivningar på maskiner och inventarier'),
  ('7832', 'Avskrivningar på inventarier och verktyg'),
  ('7840', 'Avskrivningar på förbättringsutgifter på annans fastighet'),
  ('7960', 'Valutakursförluster på fordringar och skulder av rörelsekaraktär'),
  ('7970', 'Förlust vid avyttring av immateriella och materiella anläggningstillgångar'),
  ('8010', 'Utdelning på andelar i koncernföretag'),
  ('8020', 'Resultat vid försäljning av andelar i koncernföretag'),
  ('8110', 'Utdelningar på andelar i intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i'),
  ('8210', 'Utdelningar på andelar i andra företag'),
  ('8310', 'Ränteintäkter från omsättningstillgångar'),
  ('8320', 'Värdering till verkligt värde, omsättningstillgångar'),
  ('8330', 'Valutakursdifferenser på kortfristiga fordringar och placeringar'),
  ('8410', 'Räntekostnader för långfristiga skulder'),
  ('8420', 'Räntekostnader för kortfristiga skulder'),
  ('8422', 'Dröjsmålsräntor för leverantörsskulder'),
  ('8430', 'Valutakursdifferenser på skulder'),
  ('8810', 'Förändring av periodiseringsfond'),
  ('8811', 'Avsättning till periodiseringsfond'),
  ('8819', 'Återföring från periodiseringsfond'),
  ('8830', 'Lämnade koncernbidrag'),
  ('8910', 'Skatt som belastar årets resultat'),
  ('8920', 'Skatt på grund av ändrad beskattning'),
  ('8930', 'Restituerad skatt'),
  ('8999', 'Årets resultat');

UPDATE public.chart_of_accounts c
   SET account_name = b.account_name, updated_at = now()
  FROM _bas_names b
 WHERE c.locale = 'se-bas2024'
   AND c.account_code = b.account_code
   AND c.account_name <> b.account_name;

DO $$
DECLARE v_n int;
BEGIN
  SELECT count(*) INTO v_n FROM public.chart_of_accounts c JOIN _bas_names b USING (account_code)
   WHERE c.locale = 'se-bas2024' AND c.account_name = b.account_name;
  RAISE NOTICE '% konton stämmer nu med BAS 2024', v_n;
END $$;

DROP TABLE _bas_names;

COMMIT;
