-- Forms file uploads — private storage bucket + RLS for the `file` form field type.
--
-- HISTORY: this migration used to create the `form-uploads` bucket and its
-- three policies inline. All storage DDL now lives ONLY in the always-last
-- fresh-install finalizer (99999999999999_fresh-install-finalizer.sql).
--
-- Why: on a brand-new Supabase project the platform's own storage service runs
-- its internal migrator concurrently with a GitHub-integration replay, and any
-- mid-stream migration touching storage.buckets/storage.objects can deadlock
-- (SQLSTATE 40P01 — observed live, 2026-08-10). The finalizer applies the
-- canonical bucket + policy state (read from the live fleet) once, after the
-- stream, inside a deadlock-retry loop.
--
-- This file is intentionally a no-op so already-installed instances (where it
-- is in the ledger) and fresh replays (where the finalizer owns storage) agree.
SELECT 1;
