-- The rest of the buckets that existed on some instances and in zero migrations.
--
-- `river-media` and `cowork-uploads` lived only on the instances that happened
-- to get them by hand — river's image attach failed on optic with
-- bucket-not-found. Same class as the `documents` bucket two days earlier.
--
-- HISTORY: this migration used to create both buckets, their seven policies,
-- and a bucket-completeness NOTICE inline (config read from www — the running
-- fleet is the spec). All storage DDL now lives ONLY in the always-last
-- fresh-install finalizer (99999999999999_fresh-install-finalizer.sql),
-- because a mid-stream migration touching storage.* deadlocks against the
-- storage service's own migrator on fresh projects (SQLSTATE 40P01, observed
-- live 2026-08-10). The finalizer creates all five buckets and reports counts,
-- which replaces the completeness check that used to live here.
--
-- Intentionally a no-op.
SELECT 1;
