-- The row was restricted. The bytes were not.
--
-- `20260808160000_documents-visibility.sql` gave `public.documents` a real
-- SELECT policy, so an HR document stops appearing in a salesperson's list.
-- But the FILE lives in `storage.objects`, and the documents-bucket migration
-- granted every authenticated user SELECT on the whole bucket. Both were
-- individually correct; together they produced a visibility control that reads
-- as protection and is bypassable one layer down via the storage API.
--
-- The fix defers to the table's RLS instead of restating it: policies with
-- `EXISTS (SELECT 1 FROM public.documents …)` evaluate as the querying user,
-- so the file inherits the document's visibility by construction:
--
--   "Document files follow their document's visibility"   (SELECT)
--   "Uploaders and admins can overwrite document files"   (UPDATE)
--
-- HISTORY: those two policies used to be created here inline. All storage DDL
-- now lives ONLY in the always-last fresh-install finalizer
-- (99999999999999_fresh-install-finalizer.sql) — a mid-stream migration
-- touching storage.* deadlocks against the storage service's own migrator on
-- fresh projects (SQLSTATE 40P01, observed live 2026-08-10). The finalizer
-- carries exactly these policy bodies, read from live www.
--
-- Intentionally a no-op.
SELECT 1;
