-- The documents bucket existed on three instances and in zero migrations.
--
-- Quote attachments, the documents module and upload_document all write to
-- storage bucket `documents` — created by hand on www/liteit/autoversio and
-- never committed. optic and demo were born without it, so "Upload" on a
-- quote failed with bucket-not-found and read as an RLS error.
--
-- HISTORY: this migration used to create the bucket and its four policies
-- inline (copied from www — the running fleet is the spec). All storage DDL
-- now lives ONLY in the always-last fresh-install finalizer
-- (99999999999999_fresh-install-finalizer.sql), because a mid-stream migration
-- touching storage.* deadlocks against the storage service's own migrator on
-- fresh projects (SQLSTATE 40P01, observed live 2026-08-10). Note the read/
-- update policies this file created were later superseded by
-- 20260808170000_document-files-follow-visibility — the finalizer carries the
-- superseding versions.
--
-- Intentionally a no-op.
SELECT 1;
