DELETE FROM agent_skills WHERE name IN ('openclaw_start_session','openclaw_end_session','openclaw_report_finding','openclaw_exchange','openclaw_get_status');

INSERT INTO agent_skills (name, description, category, scope, handler, enabled, origin, trust_level, tool_definition)
VALUES
  ('openclaw_start_session', 'Start a beta test session with a scenario description', 'system', 'internal', 'module:openclaw', true, 'bundled', 'auto',
   '{"type":"function","function":{"name":"openclaw_start_session","description":"Start a beta test session","parameters":{"type":"object","properties":{"scenario":{"type":"string","description":"Test scenario description"},"peer_name":{"type":"string","description":"Name of the tester"},"metadata":{"type":"object","description":"Optional metadata"}},"required":["scenario"]}}}'::jsonb),
  ('openclaw_end_session', 'End a beta test session with summary', 'system', 'internal', 'module:openclaw', true, 'bundled', 'auto',
   '{"type":"function","function":{"name":"openclaw_end_session","description":"End a beta test session","parameters":{"type":"object","properties":{"session_id":{"type":"string","description":"Session ID to end"},"summary":{"type":"string","description":"Session summary"},"status":{"type":"string","description":"Final status"}},"required":["session_id"]}}}'::jsonb),
  ('openclaw_report_finding', 'Report a bug, UX issue, or suggestion from beta testing', 'system', 'internal', 'module:openclaw', true, 'bundled', 'auto',
   '{"type":"function","function":{"name":"openclaw_report_finding","description":"Report a finding from beta testing","parameters":{"type":"object","properties":{"session_id":{"type":"string","description":"Session ID"},"type":{"type":"string","enum":["bug","ux_issue","suggestion","observation","performance"],"description":"Finding type"},"severity":{"type":"string","enum":["low","medium","high","critical"],"description":"Severity level"},"title":{"type":"string","description":"Finding title"},"description":{"type":"string","description":"Detailed description"},"context":{"type":"object","description":"Additional context"},"screenshot_url":{"type":"string","description":"Screenshot URL"}},"required":["session_id","type","title"]}}}'::jsonb),
  ('openclaw_exchange', 'Send a message between OpenClaw and FlowPilot', 'system', 'internal', 'module:openclaw', true, 'bundled', 'auto',
   '{"type":"function","function":{"name":"openclaw_exchange","description":"Exchange a message between agents","parameters":{"type":"object","properties":{"session_id":{"type":"string","description":"Optional session ID"},"direction":{"type":"string","enum":["openclaw_to_flowpilot","flowpilot_to_openclaw"],"description":"Message direction"},"message_type":{"type":"string","enum":["observation","question","suggestion","learning","acknowledgment"],"description":"Message type"},"content":{"type":"string","description":"Message content"},"payload":{"type":"object","description":"Structured payload"}},"required":["content"]}}}'::jsonb),
  ('openclaw_get_status', 'Get current beta test status', 'system', 'internal', 'module:openclaw', true, 'bundled', 'auto',
   '{"type":"function","function":{"name":"openclaw_get_status","description":"Get beta test status overview","parameters":{"type":"object","properties":{}}}}'::jsonb);