// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check if Supabase is configured
export const isSupabaseConfigured = Boolean(
  SUPABASE_URL && 
  SUPABASE_URL !== 'undefined' && 
  SUPABASE_URL !== '' &&
  SUPABASE_PUBLISHABLE_KEY && 
  SUPABASE_PUBLISHABLE_KEY !== 'undefined' && 
  SUPABASE_PUBLISHABLE_KEY !== ''
);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client only if configured, otherwise create a dummy client that will fail gracefully
export const supabase: SupabaseClient<Database> = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createClient<Database>('http://localhost:0', 'dummy-key', {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });