// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support both build-time and runtime env injection
// Runtime placeholders are replaced by docker-entrypoint.sh at container start
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '__VITE_SUPABASE_URL_PLACEHOLDER__';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '__VITE_SUPABASE_PUBLISHABLE_KEY_PLACEHOLDER__';

// Check if Supabase is configured (not placeholder or empty)
export const isSupabaseConfigured = Boolean(
  SUPABASE_URL && 
  SUPABASE_URL !== 'undefined' && 
  SUPABASE_URL !== '' &&
  !SUPABASE_URL.includes('PLACEHOLDER') &&
  SUPABASE_PUBLISHABLE_KEY && 
  SUPABASE_PUBLISHABLE_KEY !== 'undefined' && 
  SUPABASE_PUBLISHABLE_KEY !== '' &&
  !SUPABASE_PUBLISHABLE_KEY.includes('PLACEHOLDER')
);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client only if configured, otherwise create a dummy client that will fail gracefully
export const supabase: SupabaseClient<Database> = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createClient<Database>('http://localhost:0', 'dummy-key', {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });